# Generated by Django 5.2.17 on 2026-09-25 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=120)),
                ("position", models.CharField(max_length=120)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker",
                    models.CharField(
                        choices=[("candidate", "Aday"), ("interviewer", "Mülakatçı")],
                        max_length=20,
                    ),
                ),
                ("start_ms", models.PositiveIntegerField()),
                ("end_ms", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="interviews.interview",
                    ),
                ),
            ],
            options={
                "ordering": ["interview", "start_ms"],
            },
        ),
        migrations.CreateModel(
            name="QuestionSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="interviews.interview",
                    ),
                ),
                (
                    "source_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="interviews.transcriptsegment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="transcriptsegment",
            index=models.Index(
                fields=["interview", "start_ms"], name="interviews__intervi_42e85b_idx"
            ),
        ),
    ]
