# Generated by Django 5.2.17 on 2026-09-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_duration_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Mülakat', 'verbose_name_plural': 'Mülakatlar'},
        ),
        migrations.AlterModelOptions(
            name='questionsuggestion',
            options={'verbose_name': 'Soru önerisi', 'verbose_name_plural': 'Soru önerileri'},
        ),
        migrations.AlterModelOptions(
            name='transcriptsegment',
            options={'ordering': ['interview', 'start_ms'], 'verbose_name': 'Transkript parçası', 'verbose_name_plural': 'Transkript parçaları'},
        ),
    ]
